# ===============================
# APPLICATION
# ===============================

spring.application.name=backend

server.port=8080



# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5433/support_db?options=-c%20TimeZone=Asia/Kolkata

spring.datasource.username=support_user

spring.datasource.password=support_password

spring.datasource.driver-class-name=org.postgresql.Driver




# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata




# ===============================
# AI CONFIGURATION
# ===============================

ai.api.url=https://api.openai.com/v1/chat/completions

ai.api.key=${OPENAI_API_KEY}

ai.model=gpt-5-mini

# Email Configuration

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=${SUPPORT_EMAIL}

spring.mail.password=${SUPPORT_EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
# REDIS CONFIG
spring.data.redis.host=redis
spring.data.redis.port=6379

# KAFKA

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=support-group

spring.kafka.consumer.auto-offset-reset=earliest